### ISSUE TITLE
Fix Application object in "Rolling out" documentation

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#130]
As of v0.5.0-alpha.0, [the example Application object in the documentation](https://docs.shipper-k8s.io/en/latest/user/rolling-out.html#application-object) is broken. Now that chart version ranges are a thing (#105), we always try to get the repo's catalog, so Shipper fails with the following:

```
Event(v1.ObjectReference{Kind:"Application", Namespace:"default", Name:"super-server", UID:"647c0202-34a8-445a-988c-d4968dc23b54", APIVersion:"shipper.booking.com/v1alpha1", ResourceVersion:"3296014", FieldPath:""}): type: 'Warning' reason: 'FailedApplication' failed to fetch chart [name: "nginx", version: "0.0.1", repo: "https://storage.googleapis.com/shipper-demo"]: open /var/folders/1s/cn3tjbw52g14grptc443_k7r75kmg_/T/chart-cache/https-storage.googleapis.com-shipper-demo/index.yaml: no such file or directory
```

**Comment by icanhazbroccoli** [comment]
Updated in https://github.com/bookingcom/shipper/pull/182 + added a mock index.yaml to the storage.
