### ISSUE TITLE
Improve the process of building and testing Shipper locally

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#137]
Currently, it takes a lot of time to set up a local environment for testing Shipper. This makes it harder for us to test the changes in pull requests in a real world scenario, or to create the environment to reproduce an issue someone is facing.

Our plan here is to make it very easy to start testing Shipper by:

- Creating commands that easily spin off a Shipper version for testing
- Have example application objects and charts

**Comment by juliogreff** [comment]
Once #263 gets merged, we'll have our very own sample charts in the repo, so we will be able to close this.
