### ISSUE TITLE
Render *.yml templates inside charts

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#145]
Shipper suffers from a similar issue as helm did at some point: https://github.com/helm/helm/pull/3646

Probably as an oversight, we only try to render *.yaml files, and completely ignore *.yml. We should treat them both as being proper YAML.

Relevant code: https://github.com/bookingcom/shipper/blob/master/pkg/chart/chart.go#L61-L63

**Comment by icanhazbroccoli** [comment]
@ilmanzo mind opening a pull request so it can be reviewed by the team members and eventually merged?
