### ISSUE TITLE
Consider ignoring Terminating pods

### ISSUE THREAD

**Issue by laggyluke** [bookingcom/shipper#192]
Due to [a well-known Kubernetes bug](https://github.com/kubernetes/kubernetes/issues/51835), the pods can sometimes get "stuck" in Terminating state.

These Terminating pods are usually harmless as Kubernetes still maintains the desired number of healthy pods. But Shipper unfortunately still counts them, which results in a rollout getting blocked by something like this:

> WrongPodCount — expected 3 replicas but have 4

Would you please consider ignoring "Terminating" pods when calculating desired vs actual replicas?

**Comment by juliogreff** [comment]
I believe this will get fixed by #242, as when that gets merged we'll rely solely on `AvailableReplicas` to decide whether capacity has been achieved, and Terminating pods will no longer show up in `SadPods` as that doesn't get evaluated at all when capacity is achieved.

**Comment by juliogreff** [comment]
Closing this now that #242 has been merged.
