### ISSUE TITLE
Implement an end-to-end test for Shipper state metrics

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#195]
Right now, if we break Shipper state metrics, there is no way to catch this in our build pipeline. This leads to us finding out that Shipper state metrics is broken after deployment.

In this stage, all we need is a test to:

- Start Shipper state metrics
- Send a request and make sure that there is content, and the status is 200

This should help us catch the silly initial bugs, without having to verify if the data is actually correct, which is much harder to do.

**Comment by juliogreff** [comment]
Closed by #291
