### ISSUE TITLE
Strategy checks don't account for "rounding up" pod counts in traffic check

### ISSUE THREAD

**Issue by isutton** [bookingcom/shipper#22]
Breaks strategy progression when we're looking at small pod counts, similar to #7.

A possible solution is to transform weights into percentages and use the same API used when checking Capacity progress.

**Comment by kanatohodets** [comment]
Superseded by #24 -- we understood that fixing this by pulling the calculation logic up into the Strategy controller breaks the abstraction we're trying to present with the Traffic controller.
