### ISSUE TITLE
Should we retire the fleet summary?

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#279]
The fleet summary (#21) was introduced to help users diagnose rollout progress. It was part one of a two step strategy: a low-level summary in the CapacityTarget, while a higher-level one would be created at the Release level (#139). This was implemented way before we ever thought that one day Shipper we'd have Shipper objects spread into application clusters as well (#272).

Now that we are indeed moving CapacityTargets away from the management cluster, users would need to check each application cluster for their CapacityTargets and their summary. I'm of the opinion that at this point, users are better off just looking at the Pods directly instead of combing through our summaries.

This raises the question: do we still want to keep the fleet summary? Especially after #139 gets addressed, I feel like we're not getting the value that the original idea was supposed to give us. So I propose that after both #277 and #139 are done, we completely remove the fleet summary in favor of a Release level summary.

What do you guys think?

**Comment by icanhazbroccoli** [comment]
The breakdown argument sounds very reasonable to me. In practice, users rarely go further than checking release objects and having this information spread around the clusters doesn't sound shiny to me personally. Good initiative!
