### ISSUE TITLE
Run Shipper webhook on app clusters, too

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#350]
Currently, the webhook only exists in the management cluster, which means that some of the sanity checks we have in the webhook (e.g. making sure that the object deserializes correctly) are not running in application clusters. This means that a wrong YAML object, for example, could break Shipper in the relevant application cluster.

**Comment by kanatohodets** [comment]
This seems like it can be closed, given that we're not moving ahead right now with the app cluster Shipper agent.
