### ISSUE TITLE
Deprecate listening to InstallationTarget, CapacityTarget and TrafficTarget in shipper-mgmt

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#351]
Right now, there is a discrepancy between how `shipperctl` sets up a cluster and what `shipper-mgmt` expects it to be. `shipperctl` doesn't create CRDs for target objects because they are moved to the application clusters, but `shipper-mgmt` listens to them because of the migration process.

We can solve this discrepancy by deprecating listening to these target objects in the next version after Shipper 0.9.0 – could be even 0.9.1!

**Comment by kanatohodets** [comment]
This seems like it can be closed, given the plan to abort on the 0.9 rearchitecture. Is that accurate?
