### ISSUE TITLE
Create a Shipperctl Command to Validate Helm Charts

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#46]
Right now, there is no quick and easy way to figure out what Helm charts work with Shipper. It would be great if we could provide a command to check a chart against our constraints.

Here are the benefits for this approach:

- Users can validate the charts they've written before installing it
- Users can validate Helm charts in the stable repo before using them

One thing that needs mentioning here is that the scope of this command should only be to check the chart against Shipper constraints. We're not telling users if their objects will install or work as expected – we're only telling them that it would pass Shipper's rudimentary checks.

**Comment by icanhazbroccoli** [comment]
A PR is ready to be reviewed: https://github.com/bookingcom/shipper/pull/59
