### ISSUE TITLE
Make Our E2E Tests Choose the Right Region

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#48]
Right now we're hard-coding our tests to use the `eu-west` region. However, with the introduction of `shipperctl admin clusters apply`, people could define their own clusters very easily and run tests against those. We should retrieve that cluster and use its region instead of hard-coding the region when creating cluster requirements.

**Comment by kanatohodets** [comment]
#50 addresses this

**Comment by kanatohodets** [comment]
Fixed because #50 was merged!
