### ISSUE TITLE
Move target object creation from Schedule Controller to Application Controller

### ISSUE THREAD

**Issue by isutton** [bookingcom/shipper#6]
## Rationale

In the current implementation the Schedule Controller is responsible, in addition of finding suitable clusters for a Release to be installed, for creating the Installation, Capacity and Traffic target objects related to such Release. Making this creation of objects part of Schedule Controller's responsibility seems off (perhaps better wording in here).

It is currently the responsibility of the Application Controller create new Release objects once an Application object's `.spec.template` field is modified. This new Release object is then marked as *schedulable* (that is, setting the Release condition type **Scheduled** to status **True**), then triggering the Schedule Controller to perform the aforementioned operations.

This proposal is about **moving the responsibility of creating Installation, Capacity and Traffic target objects from Scheduler Controller to the Application Controller**. 

This means that, in addition to create the Release object reflecting an Application object's `.spec.template` field, the **Application Controller will also create the supporting Installation, Capacity and Traffic target objects**. It also means that the operations on Scheduler Controller would change as well: the **Schedule Controller's sole responsibility becomes finding suitable clusters for a Release object and modify all the Release related target objects**.

### Benefits

An outside reader might consider surprising when discovering the Schedule Controller is responsible for unpacking and decoding charts and propagating Release conditions; it is also surprising is also its responsibility to create the Release related target objects.

The main benefit of this proposal is a more well defined and predictable boundaries between Application and Schedule controller, and their interactions with the Release related target objects.

### Application Controller

The following list describes the high-level operations expected at a single Application sync on Application Controller if this proposal is implemented. Not including other Application Controller responsibilities like handling roll backs in here is intentional.

* Creates a new Release object using Application object's `.spec.template`.
* Creates a new Installation target object with empty `.spec` field having the new Release object as owner.
* Creates a new Capacity target object with empty `.spec` field having the new Release object as owner.
* Creates a new Traffic target object with empty `.spec` field having the new Release object as owner.
* Determines chart health (whether a chart could be fetched, parsed and decoded successfully) and extracts from it required information by target objects.
    * Stores the chart into the cache location. Failing to do so will be reflected in the **ChartCached** Release condition.
* Updates relevant target objects if chart is healthy.
    * Set `shipper.booking.com/capacity.replica-count` annotation in Capacity target object to be consumed by the Schedule Controller and used in `.spec.clusters[].totalReplicaCount` when updating `.spec.clusters`.
* Updates Release conditions based on the chart's health.
    * **ChartCached/False**
        * **CacheError**: Chart is reachable but couldn't be stored into the cache location. This can be used by other actors to avoid using the cache infrastructure and try to fetch the chart directly from the specified repository as last resort before failing.
    * **ChartCached/True**
        * Chart was properly stored into the cache location.
    * **ChartHealthy/False**
        * **NotReachable**: Chart is not reachable due to some HTTP error (not found, server error, etc).
        * **SyntaxError**: Chart can not be rendered due to syntax errors. This error is not recoverable.
        * **DecodeError**: Chart could be rendered but couldn't be decoded into valid Kubernetes manifests. This error is not recoverable.
        * **ShipperContractError**: Chart could be rendered but doesn't fulfill Shipper's contract, for example more than one Deployment manifest being rendered, or missing required Service manifest.
    * **ChartHealthy/True**
        * Chart has been downloaded and processed successfully.

### Scheduler Controller

The following list describes the high-level operations expected at a single Release sync on Scheduler Controller if this proposal is implemented.

* Finds suitable clusters for the Release object.
* Updates `shipper.booking.com/release.clusters` annotation in Release object.
    * Failure in updating the Release object should abort the sync handler and re-enqueue the Release.
* Updates Installation target object's `.spec.clusters` with selected cluster names.
* Updates Capacity target object's `.spec.clusters`, setting for each cluster the `.spec.clusters[].percent` field with `0`, and `.spec.clusters[].totalReplicaCount` with the value set in `shpper.booking.com/capacity.replica-count`. 
* Updates Traffic target object's `.spec.clusters`, setting for each cluster the `.spec.clusters[].weight` field with `0`.
* Updates Release conditions based on cluster selection result and whether all related target object's have been updated.
    * **Scheduled/False**
        * **NoClusters**: No clusters have been found matching Release's `.spec.clusterRequirements`.
        * **TargetObjectMissingClusters**: Not all target objects have been updated to match Release selected clusters. Message should contain the objects which `.spec` is incorrect. Example: `it/reviews-api-deadbeef-0, ct/reviews-api-deadbeef-0`.
    * **Scheduled/True**
        * Schedule Controller was able to find suitable clusters to scheduled the Release and update all Release related target objects.

### Strategy Controller

It is likely that no modifications in Strategy Controller are required for this proposal, since the Strategy Controller will not interact with target objects until the Release has been *scheduled* (by checking the **Scheduled** Release condition).

### Installation Controller

This proposal is based on the premise that Installation Controller can handle Installation target objects with an empty `.spec`, so this implementation should add or increase test coverage in cases where Installation target objects have empty `.spec` field.

### Capacity Controller

This proposal is based on the premise that Capacity controller can handle Capacity target objects with an empty `.spec`, so this implementation should add or increase test coverage in cases where Capacity target objects have empty `.spec` field.

### Traffic Controller

This proposal is based on the premise that Traffic Controller can handle Traffic target objects with an empty `.spec`, so this implementation should add or increase test coverage in cases where Traffic target objects have empty `.spec` field.

**Comment by kanatohodets** [comment]
Superseded by #37
