### ISSUE TITLE
Release Controller Should Enforce State For All Releases Based On Their Successor If Found

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#71]
Right now Shipper only reacts to the last two releases, the incumbent and contender. This means that if there is a problem in a release that is not either the incumbent and contender, it will stay there for ever.

This issue showed itself with a Release object that was supposed to be completely rolled out. however, for some reason, the `spec` of the CapacityTarget and TrafficTarget were still saying that this release should have _10%_ capacity and _10%_ traffic.

In a perfect world, Shipper would do the following:

1. Receive an update event for an old Release
2. Find out the next release in the history, the _newer_ Release
3. Figure out what state the associated target objects (`InstallationTarget`, `CapacityTarget`, and `TrafficTarget`) of the _old_ release should be, based on the _newer_ release
4. Apply that to the target objects

**Comment by icanhazbroccoli** [comment]
This issue is planned to be fixed with the upcoming merge request #70. The relevant e2e tests are to be delivered asap.

**Comment by icanhazbroccoli** [comment]
Implemented in https://github.com/bookingcom/shipper/pull/254. Will close the ticket once it gets merged (due release version: 0.8)

**Comment by icanhazbroccoli** [comment]
#254 got merged into master, closing this ticket.
