### ISSUE TITLE
Store the Shipper deployment object in our repository

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#74]
Currently, Shipper's deployment object is a release artefact that we're keeping in Github.

- We should bring it into our repository, so that it's easy to modify, and takes no extra toil
- We should update the documentation to point to this new URL

The first item is done in pull request #60, so we should wait for that to be merged first. Once that's done, we can clean it up and update it, then update the documentation to point to it.

**Comment by juliogreff** [comment]
We now have a deployment object that we use in our CI pipeline after #86 got merged, so now we just need to point our documentation to it.

**Comment by juliogreff** [comment]
Fixed by #182
