### ISSUE TITLE
Shipper Should Stop Re-processing All Objects Over and Over

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#78]
Right now, after each resync, we process all Shipper objects that exist in Kubernetes, even those that haven't changed at all.

This has two side effects:

1. Our queues get longer and longer as more objects are added to our clusters, because we process all of them and don't do any selective filtering
2. Our API requests are unnecessarily high, which means that at some point, we keep hitting our API request throttling limit.

**Comment by ksurent** [comment]
> Right now, we process all objects repeatedly, even those that haven't changed at all.

How so? You mean during resyncs?

**Comment by parhamdoustdar** [comment]
Sorry, went back and edited the issue to make it clearer.

So, the issue is that when we get an update on all objects on every resync,  all those objects get added to our queue, and get processed again.

**Comment by juliogreff** [comment]
As far as we know, this can be addressed once #206 and #207 have been closed. After that, we just need to disable resyncs by default.
