### ISSUE TITLE
Define Better Printing Columns For Our Custom Resources

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#79]
Shipper CRDs are currently not taking advantage of the capabilities added in Kubernetes 1.13 for defining printing columns. These are great for improving the user experience of Shipper, so it's important for us to define and surface useful information at each level.

#67 already discusses this for Release objects, but we need to define this for other CRDs such as Application and target objects as well.

**Comment by juliogreff** [comment]
Closed by #287 and #289
