### ISSUE TITLE
The 'Complete' condition on Release objects prevents them from respecting changes in targetStep

### ISSUE THREAD

**Issue by isutton** [bookingcom/shipper#9]
When a release is marked as 'complete', it will no longer respect changes made to targetStep, even if it remains the head of history. This means that 'graceful' linear rollbacks are not possible once the strategy is complete.

**Comment by isutton** [comment]
From what I remember, we only designed graceful linear rollbacks for releases that were not completed yet. 

For completed releases, we envisioned that removing the release would bring the previous release back *as fast as possible* to activity even if it means increasing request time-outs and other sort of capacity related issues until the previous release has been fully deployed.

This behavior was designed for situations where the release was successful (Pods are started successfully) but there's some business logic error encoded in the application (for example storing corrupt data), where a graceful linear rollback wouldn't help much.

**Comment by isutton** [comment]
We have, in my opinion, two options:

1. Disallowing any changes on a completed Release object's `.spec.targetStep` field once the it is fully rolled out. This means that the user can either remove the currently active Release object to rollback to the previous release (if any), or change the Application `.spec.template` field which will trigger a new Release object to be created.
2. Allow changes to the Release `.spec.targetStep` field of the **current contender Release object** after the release has been rolled out, meaning that the user could rewind the targetStep value to any valid step.

#2 should already be in place to implement 1). I personally have mixed feelings about this approach but can't currently pinpoint exactly why.

I can see the benefits of 2), specially on a fire-fighting situation where one could easily rewind capacity and traffic to the previous known state. 

Regardless of choosing between 1) or 2), #2 should be in place to make sure that **incumbent Release objects**'s `.spec` fields can't be modified (unless this Release object become the contender Release through a rollback action).

**Comment by juliogreff** [comment]
Somewhere along the way this got fixed by other means, so it is currently possible to step backwards from a completed contender. Closing this.
