### ISSUE TITLE
Check compatibility with Kubernetes 1.13 & 1.14

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#94]

**Comment by kanatohodets** [comment]
Not sure if we'll be using Travis forever, but https://hub.docker.com/r/kindest/node/tags will let us specify `--image=kindest/node:v1.$some.$version`, and in conjunction with https://docs.travis-ci.com/user/build-stages/matrix-expansion/ we could run tests against a range of K8s versions.

**Comment by juliogreff** [comment]
Even if we end up breaking up with Travis, I believe most CI platforms would support that. I just worry a little bit about build times, but I'll test it out and see how bad it is.
