### ISSUE TITLE
Only replace the services created by this Application object

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#98]
If there are two Application object that both render charts with the same Service object, Shipper will constantly replace the Service.

This started happening when a user had two Application objects, and passed the same Service name  as one of the values in the chart for both applications. What happened was that Shipper started replacing the Service object over and over.

**Comment by icanhazbroccoli** [comment]
Frankly, that sounds like a conflicting input, which I personally would place on the same shelf as dual set of production-labeled services.

**Comment by parhamdoustdar** [comment]
Can you explain a bit on what you mean in terms of how Shipper should behave? Do you mean that it should error out just as it does when two services have the `shipper-lb` label set?

**Comment by juliogreff** [comment]
There's a good opportunity here to also take care of #12 :)

**Comment by juliogreff** [comment]
Closed by #223
